services:
  nodejs:
    build:
      context: ./backend
    container_name: node-backend
    environment:
      MONGO_URI: "YOUR_KEY"
      JWT_TOKEN: "mysupersecretkey123"
    ports:
      - "5000:5000"
    networks:
      - inventory
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  react:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:80"
    restart: always
    depends_on:
      - nodejs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  inventory:
